### ISSUE TITLE
Needs vscode plugin with debugger

### ISSUE THREAD

**Issue by Meai1** [oridb/mc#133]
This kinda makes a vscode language server in myrrdin necessary, (for autocompletion)

**Comment by andrewchambers** [comment]
If vscode supports general GDB debugging, this will probably come first. Currently the debug symbols are lacking, but we are aware of the issues and what work needs to be done to fix it.

**Comment by oridb** [comment]
I have no idea what vscode needs -- I have no objection to including this under support/, or linking to a separate repository, but this will probably need someone who uses vscode to implement it.

As far as debugging goes, I think that after we finish moving to a new backend (QBE), we'll start putting significant effort into generating dwarf debug information. For now, debugging with prints is feasible, as is using gdb to look at the assembly. 

It's also probably time to switch the compiler to generate source line mappings, instead of putting them into comments in the assembly -- comments in the assembly were more useful earlier on, but I tend to use them more rarely now.
