### ISSUE TITLE
Unable to create an alias to a function type

### ISSUE THREAD

**Issue by rcorre** [oridb/mc#141]
Is it possible to declare a type that refers to a function signature?

If so, why is it that `f1` compiles but `f2` fails with `type "fun" incompatible with "(int -> int)" near f2:fun
`?

If not, what exactly did I declare `fun` to be?

```
type fun = (x: int -> int)

const main = {
	var f1 : (x: int -> int) = {x: int
		-> 1
	}
	var f2 : fun = {x: int
		-> 1
	}
}
```

**Comment by oridb** [comment]
On Mon, 05 Jun 2017 05:34:00 -0700
Ryan Roden-Corrent <notifications@github.com> wrote:

> Is it possible to declare a type that refers to a function signature?

Yes. Sort of. But the type is going to be a new, incompatible type.

> 
> If so, why is it that `f1` compiles but `f2` fails with `type "fun" incompatible with "(int -> int)" near f2:fun
> `?
> 
> If not, what exactly did I declare `fun` to be?

You created a new type based on the function.

	type foo = bar

creates a new, incompatibe type and not an alias. Currently,
functions don't participate in delayed unification, so you
get a type error when you assign from a function to the new
type -- you need to cast.

I've been debating changing this in one way or another; either
adding type aliases to the language, or making functions participate
in delayed unification.

> ```
> type fun = (x: int -> int)
> 
> const main = {
> 	var f1 : (x: int -> int) = {x: int
> 		-> 1
> 	}
> 	var f2 : fun = {x: int
> 		-> 1
> 	}
> }
> ```

	var f2 = (f1 : fun)

will work. It's a bit clunky.


-- 
Ori Bernstein <ori@eigenstate.org>

**Comment by rcorre** [comment]
Thanks for explaining. I just realized my use case might not be relevant anyways. I'm binding to a C library that typedefs some function callbacks, but I'm guessing I can't pass myr functions to those.

**Comment by oridb** [comment]
You can. You need to cast them to a pointer, though. And the environment
is lost when you do this, so you can only really do it safely with global
functions, rather than inner ones.

For a peek at how to do it, take a look at how I install signal handlers
in lib/sys/setup+posixy.myr:

	/* is there ever a time we care about sigpipe? */
	sa = [
		.handler = ({;} : byte#),
		.flags = sys.Sarestart,
	]
	sys.sigaction(Sigpipe, &sa, &osa)

Like slices, a closure can be cast to a pointer which points at the code. This
is about as C ABI compatible as any other Myrddin function is.

You actually *can* do some games to get back a closure if your C code lets you
pass a void pointer to your function -- lib/std/fndup.myr implements the code
that assembles, deassembles, and prods at functions, for an idea of how it
would work.

On Mon, 05 Jun 2017 12:26:48 -0700
Ryan Roden-Corrent <notifications@github.com> wrote:

> Thanks for explaining. I just realized my use case might not be relevant anyways. I'm binding to a C library that typedefs some function callbacks, but I'm guessing I can't pass myr functions to those.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/oridb/mc/issues/141#issuecomment-306278844


-- 
Ori Bernstein <ori@eigenstate.org>
