### ISSUE TITLE
Faulty occurs check

### ISSUE THREAD

**Issue by iitalics** [oridb/mc#145]
The occurs check fails to prevent infinite types, which crash the typechecker:

```
use std
const main = {
    var a = [`std.None]
    a[0] = `std.Some(a)
}
```

According to the source;
```c
/* Checks if a type that directly contains itself.
 * Recursive types that contain themselves through
 * pointers or slices are fine, but any other self-inclusion
 * would lead to a value of infinite size */
static int
occurs_rec(Type *sub, Bitset *bs)
```

Usually, the "occurs check" isn't there to prevent types of infinite size, it's to stop a type variable from containing itself, which is always invalid and will end up crashing unification later on.

**Comment by oridb** [comment]
> Usually, the "occurs check" isn't there to prevent types of infinite size, it's to stop a type variable from containing itself, which is always invalid and will end up crashing unification later on.

This accomplishes both. In most languages where this check is relevant, as far as I recall, types are (at least conceptually) references, so putting a type inside itself verbatim doesn't create an explosion in size.

In any case, the root cause was that we weren't looking up the unified type of the variable, so we were missing it in the other type. For example in a slightly simpliefied version of your case, the type of `a` was `$59`, but we had already been unified with the type variable `$66` in the union. As a result, $59 did not occur in the union, but the value it had been unified with did.
