### ISSUE TITLE
runtest.sh pkgtrait test failure

### ISSUE THREAD

**Issue by Earnestly** [oridb/mc#152]
Hi,

When attempting to run `make check` I'm getting this one test failure, which seems to result in 2 `FAILURES`, the `runtest.sh` itself and `runtest.sh/pkgtrait` (shouldn't this only be one failure?):

```
	run pkgtrait:	pkgtrait: regex does not exist in ../lib/std ../lib/sys ../lib /usr/local/lib/myr
./runtest.sh: line 30: ./pkgtrait: No such file or directory
FAIL pkgtrait
```

I found this patch to "fix" it:

```diff
diff --git a/test/runtest.sh b/test/runtest.sh
index 020fdef1..feaa7b45 100755
--- a/test/runtest.sh
+++ b/test/runtest.sh
@@ -10,7 +10,7 @@ NPASSES=0
 build() {
        rm -f $1 $1.o $1.s $1.use
        echo ../obj/mbld/mbld -o '' -b $1 -I../lib/std -I../lib/sys -r../rt/_myrrt.o $1.myr
-       ../obj/mbld/mbld -o '' -b $1 -I../lib/std -I../lib/sys -r../rt/_myrrt.o $1.myr
+       ../obj/mbld/mbld -o '' -b $1 -I../lib/std -I../lib/sys -I../lib/regex -r../rt/_myrrt.o $1.myr
 }
 
 pass() {
```

The same would be applied to the rc script as well.  But I assume this is not ideal since there is more than just `../lib/regex` and if future tests use those facilities it would need to be parameterised in some way.

**Comment by oridb** [comment]
On Sat, 18 Nov 2017 20:03:06 +0000 (UTC), Earnestly <notifications@github.com> wrote:

> ```diff
> diff --git a/test/runtest.sh b/test/runtest.sh
> index 020fdef1..feaa7b45 100755
> --- a/test/runtest.sh
> +++ b/test/runtest.sh
> @@ -10,7 +10,7 @@ NPASSES=0
>  build() {
>         rm -f $1 $1.o $1.s $1.use
>         echo ../obj/mbld/mbld -o '' -b $1 -I../lib/std -I../lib/sys -r../rt/_myrrt.o $1.myr
> -       ../obj/mbld/mbld -o '' -b $1 -I../lib/std -I../lib/sys -r../rt/_myrrt.o $1.myr
> +       ../obj/mbld/mbld -o '' -b $1 -I../lib/std -I../lib/sys -I../lib/regex -r../rt/_myrrt.o $1.myr
>  }
>  
>  pass() {
> ```

Will apply, with a few changes.
 
> The same would be applied to the rc script as well.  But I assume this is
> not ideal since there is more than just `../lib/regex` and if future tests
> use those facilities it would need to be parameterised in some way.

I see you haven't run make install, or it would be picking up the installed
versions, and you'd be seeing a semi-bogus success, like I do. ;-)

Parameterising these tests transparently is going to be hard, but we can at
least make them fail nicely if we give the `-B none` option to tell it we
have no installation base dir.

And the last change: `mbld` was changed to build into `obj/`; the only thing
that puts `.o` files into ../lib and friends is the bootstrap script.

So, with those differences, the fix is pushed.

-- 
    Ori Bernstein

**Comment by Earnestly** [comment]
Yes indeed, I am running the tests prior to `make install`.  It makes things
a lot more straight foward when doing staged installations this way.

Many thanks again o/
