### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [oridb/mc#182]
Hi @oridb  . I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design. I'll be doing it as a gift for free to your awesome project.

Best Regard.
Mirza Zulfan

**Comment by mirzazulfan** [comment]
Hi @kirbyfan64 .. What do you think ?  Does this project need a logo?  Sorry for that. :+1:

**Comment by phase** [comment]
A cool logo and a proper social media strategy would definitely give this language the love it deserves.

**Comment by oridb** [comment]
Sorry for the delayed response -- I've beey pretty busy. We do have a "nice" logo, since we needed one to apply for Summer of Code. We don't have a ridiculous one that really fits the character of the project (ie, makes fun of the whole endeavor).

![myrlogo-gray](https://user-images.githubusercontent.com/5384580/43738766-a42172b0-997a-11e8-88fa-be07e72fd0f7.png) 

As far as a social media strategy -- uh.
