### ISSUE TITLE
assertion failure in type checker

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#27]
```
ac@nomad:~/Desktop/bug$ mbld -b bug bug.myr
bug...
	6m	bug.myr 
6m: infer.c:500: tf: Assertion `orig != ((void *)0)' failed.
CRASH: "6m bug.myr"
```

The reader functions are not defined yet, so that might be the cause.

```
use std
use bio

pkg pack =
	type writer = struct
		f       : bio.file#
		offsets : std.htab(byte[20], uint64)#
		offset  : uint64
	;;
	type reader = struct
		f : bio.file#
	;;
	const newwriter   : (path : byte[:] -> std.result(writer#, byte[:]))
	const add   : (w : writer#, k : byte[20], v : byte[:] -> std.result(void, byte[:]))
	const closewriter : (w : writer# -> std.result(void, byte[:]))

	const newreader   : (path : byte[:] -> std.result(writer#, byte[:]))
	const get         : (r : reader#, k : byte[20] -> std.result(byte[:], byte[:]))
	const closereader : (r : reader# -> std.result(void, byte[:]))
;;

const khash = {v : byte[20]
	-> std.strhash(v[:])
}

const keq = {a : byte[20], b : byte[20]
	for var i = 0; i < a.len; i++
		if a[i] != b[i]
			-> false
		;;
	;;
	-> true
}

const newwriter = {path
	var w : writer#
	
	match bio.open(path, bio.Wr)
	| `std.Ok f:
		w = std.alloc()
		w.offset = 0
		w.offsets = std.mkht(khash, keq)
		w.f = f
		-> `std.Ok(w)
	| `std.Fail msg:
		-> `std.Fail(msg)
	;;
}

const add = {w, k, v
	if std.hthas(w.offsets, k)
		-> `std.Ok(void)
	;;
	std.htput(w.offsets, k, w.offset)
	match bio.write(w.f, v)
	| `bio.Ok sz: 
		if sz != v.len
			std.fatal("short write on pack file")
		;;
	| `bio.Err e:
		std.fatal("io error writing pack file")
	| `bio.Eof:
		std.fatal("eof writing pack file")
	;;
	w.offset += v.len
}

const closewriter = {w
	
	-> `std.Ok(void)
}
```

**Comment by oridb** [comment]
It looks like we're trying to use the array length before it has a type attached. I'm going to track down why this is happening.

**Comment by oridb** [comment]
The root cause is that we walk all declarations to infer the types, but then use the symbol table to output the types. We also don't attach a type directly to the array length at creation time, but instead do it when we infer. Normally, this is fine, since the only extra declarations we hit this way are the fully typed imports that we need to rexport, however in this case there are functions with no implementation that we end up hitting.

We shouldn't crash -- this is fixable by giving the array size a type variable when we create it -- but for workign around it, you can also just make sure that the functions that are declared have a definition too.

**Comment by oridb** [comment]
And I need to stop hitting 'close and comment' instead of just 'comment'.

**Comment by oridb** [comment]
Turns out that this was only affecting declarations that had no definition; There was code that tried to disallow that, but it had broken at some point.

Fixed.
