### ISSUE TITLE
Add extension to merged use files

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#50]
something like .muse, it makes it easier to .gitignore them with a wildcard like *.muse.

**Comment by oridb** [comment]
how about libfoo.use, to match libfoo.a?

**Comment by andrewchambers** [comment]
that would be fine by me. I can probably try to do this fix since it is probably pretty small.

**Comment by oridb** [comment]
If you're going to make this change, it might be worth looking at allowing dropping ".use" from the quoted use statements.

Another minor todo on that front is making the search path start at the file loaded, instead of the cwd of the compiler, so '6m lib/std/foo.myr' won't give errors about not being able to find the files loaded from lib/std.

These changes should probably be separate commits.

**Comment by oridb** [comment]
Did it already. Cleaning up old bugs.
