### ISSUE TITLE
infinite loop with post decrement on an integer

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#70]
```
use std

const main = {
    var x = 100
    while x-- > 0
    ;;
    for x = 100; x-- > 0; 
    ;;
    std.put("pass\n")
}
```

found by mpu

**Comment by kirbyfan64** [comment]
FYI, the second loop is unnecessary to reproduce this. Just the first hangs forever; `x` apparently never actually gets decremented.

**Comment by oridb** [comment]
This happens because 6m collects postincrements/decrements to emit after the expression is evaluated. The problem: This ends up turning into:

      cjmp x > 0: .Ltrue, .Lfalse
      inc x
      .Ltrue:
            stuff
      .Lfalse:
            stuff

The inc gets dropped as unreachable. To fix this, we'd have to valuate the comparison expression into a temp, emit the postmodifications, and then jump based on the temp.

**Comment by andrewchambers** [comment]
I added the second loop so we test both but yeah. Not needed.
